function interactionmanager(){var Q='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',jb='"><\/script>',$='#',gc='.cache.html',ab='/',Yb='033FFFCC156465A25AA44A3EF4BEF8BF',Zb='1FDD4E317520743A4BE926FA22306600',$b='679FBAEC4A1A9E74BF5F06CDFF5BF125',_b='82BF81D61207416FED275767918E9296',ac='8A6CFE1EC119B2FCD6824F876A625648',fc=':',pb='::',oc='<script defer="defer">interactionmanager.onInjectionDone(\'interactionmanager\')<\/script>',ib='<script id="',sb='=',_='?',bc='BAA19C4F12B9F2302DC9AA786095CF3E',cc='BE00634B11389F41D02BB5B1CF2F263B',ub='Bad handler "',Fb='DEBUG',nc='DOMContentLoaded',dc='E8776DE1FD78853327A888206A77AE48',Ib='ERROR',ec='F44E9206A3C06A6E04455F28DDD9D6E6',Jb='FATAL',Gb='INFO',Kb='OFF',kb='SCRIPT',Eb='TRACE',Hb='WARN',Db='[\\?&]log_level=([^&#]*)',hb='__gwt_marker_interactionmanager',lb='base',db='baseUrl',U='begin',T='bootstrap',cb='clear.cache.gif',rb='content',Z='end',Sb='gecko',Tb='gecko1_8',V='gwt.codesvr=',W='gwt.hosted=',X='gwt.hybrid',hc='gwt/standard/standard.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',mc='head',Wb='hosted.html?interactionmanager',lc='href',Rb='ie6',Qb='ie8',yb='iframe',bb='img',R='interactionmanager',fb='interactionmanager.nocache.js',ob='interactionmanager::',zb="javascript:''",ic='link',Vb='loadExternalRefs',Cb='log_level',mb='meta',Bb='moduleRequested',Y='moduleStartup',Pb='msie',nb='name',Mb='opera',Ab='position:absolute;width:0;height:0;border:none',jc='rel',Ob='safari',eb='script',Xb='selectingPermutation',S='startup',kc='stylesheet',gb='undefined',Ub='unknown',Lb='user.agent',Nb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=Q,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:U});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(V)!=-1||(c.indexOf(W)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(X)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(R);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return I(a)}}interactionmanager=null;c.gwtOnLoad(z,R,t,y);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Z})}}
function D(){function e(a){var b=a.lastIndexOf($);if(b==-1){b=a.length}var c=a.indexOf(_);if(c==-1){c=a.length}var d=a.lastIndexOf(ab,Math.min(c,b));return d>=0?a.substring(0,d+1):Q}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(bb);b.src=a+cb;a=e(b.src)}return a}
function g(){var a=G(db);if(a!=null){return a}return Q}
function h(){var a=n.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(fb)!=-1){return e(a[b].src)}}return Q}
function j(){var a;if(typeof isBodyLoaded==gb||!isBodyLoaded()){var b=hb;var c;n.write(ib+b+jb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=kb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return Q}
function k(){var a=n.getElementsByTagName(lb);if(a.length>0){return a[a.length-1].href}return Q}
var l=g();if(l==Q){l=h()}if(l==Q){l=j()}if(l==Q){l=k()}if(l==Q){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,Q);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,j=g.indexOf(sb);if(j>=0){f=g.substring(0,j);h=g.substring(j+1)}else{f=g;h=Q}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a,b){return b in v[a]}
function G(a){var b=u[a];return b==null?null:b}
function H(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function I(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var J;function K(){if(!J){J=true;var a=n.createElement(yb);a.src=zb;a.id=R;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+M)}}
w[Cb]=function(){var a;if(a==null){var b=new RegExp(Db);var c=b.exec(location.search);if(c!=null){a=c[1]}}if(a==null){a=G(Cb)}if(!F(Cb,a)){var d=[Eb,Fb,Gb,Hb,Ib,Jb,Kb];var e=null;var f=false;for(i in d){f|=a==d[i];if(F(Cb,d[i])){e=d[i]}if(i==d.length-1||f&&e!=null){a=e;break}}}return a};v[Cb]={INFO:0,OFF:1};w[Lb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Mb)!=-1){return Mb}else if(b.indexOf(Nb)!=-1){return Ob}else if(b.indexOf(Pb)!=-1){if(document.documentMode>=8){return Qb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Rb}}}}else if(b.indexOf(Sb)!=-1){return Tb}return Ub};v[Lb]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};interactionmanager.onScriptLoad=function(){if(J){r=true;C()}};interactionmanager.onInjectionDone=function(){q=true;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Vb,millis:(new Date).getTime(),type:Z});C()};E();D();var L;var M;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(R))){m.location.reload();return}M=Wb;L=Q}o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Xb});if(!B()){try{H([Kb,Rb],Yb);H([Kb,Qb],Yb);H([Kb,Tb],Zb);H([Gb,Ob],$b);H([Kb,Ob],_b);H([Kb,Mb],ac);H([Gb,Rb],bc);H([Gb,Qb],cc);H([Gb,Tb],dc);H([Gb,Mb],ec);L=x[I(Cb)][I(Lb)];var N=L.indexOf(fc);if(N!=-1){y=Number(L.substring(N+1));L=L.substring(0,N)}M=L+gc}catch(a){return}}var O;function P(){if(!s){s=true;if(!__gwt_stylesLoaded[hc]){var a=n.createElement(ic);__gwt_stylesLoaded[hc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+hc);n.getElementsByTagName(mc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(nc,P,false)}if(O){clearInterval(O)}}}
if(n.addEventListener){n.addEventListener(nc,function(){K();P()},false)}var O=setInterval(function(){if(/loaded|complete/.test(n.readyState)){K();P()}},50);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Z});o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Vb,millis:(new Date).getTime(),type:U});n.write(oc)}
interactionmanager();